idf_component_register(
    SRCS
        "mode_ctrl.c"
        "mode0.c"
        "mode1.c"
        "mode2.c"
        "mode3.c"
        "mode4.c"
        "mode4_zhongyao_v2.c"
        "mode5.c"
        "mode_test.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        driver
        ctrl_protocol
        esp_adc
        modbus
        My_Bt
)
