idf_component_register(
    SRCS
        "src/modbus_master.c"
        "src/massage_chair.c"
        "src/inverter.c"
        "src/temp.c"
    INCLUDE_DIRS
        "include"
        "${CMAKE_SOURCE_DIR}/managed_components/espressif__esp-modbus/modbus/mb_controller/common/include"
    REQUIRES
        driver
        espressif__esp-modbus
)
